index:
    path: /
    controller: App\Controller\HomeController::index

app_lucky_number:
    path: /lucky/number/{max}
    controller: App\Controller\LuckyController::number
    defaults:
        max: 100
    requirements:
        max: '\d+'

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET
