index:
    path: /
    controller: App\Controller\HomeController::index

app_lucky_number:
    path: /lucky/number/{max}
    controller: App\Controller\LuckyController::number
    defaults:
        max: 100
    requirements:
        max: '\d+'

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

app_logout:
    path: /logout
    methods: GET

profile_show:
    path: /profile-show
    controller: App\Controller\IUserController::profileShow

profile_edit:
    path: /profile-edit
    controller: App\Controller\IUserController::profileEdit

profile_new:
    path: /profile-new
    controller: App\Controller\IUserController::profileNew
